<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<properties>
		<revision>2.2.9-SNAPSHOT</revision>
	</properties>
	<parent>
		<groupId>nl.uu.fi.dwo</groupId>
		<artifactId>DWO.master.pom</artifactId>
		<version>1.1</version>
	</parent>
	<artifactId>EBDocker</artifactId>
	<version>${revision}</version>
	<name>Docker voor EBServer</name>
	<dependencies>
		<dependency>
			<groupId>nl.uu.fi.dwo</groupId>
			<artifactId>EBServer</artifactId>
			<version>${project.version}</version>
			<type>war</type>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>2.10</version>
                <executions>
                    <execution>
                        <id>copy</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>copy</goal>
                        </goals>
                       <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>${project.groupId}</groupId>
                                    <artifactId>EBServer</artifactId>
                                    <version>${project.version}</version>
                                    <type>war</type>
                                    <overWrite>true</overWrite>
                                    <destFileName>ROOT.war</destFileName>
                                </artifactItem>
                            </artifactItems>
                            <overWriteReleases>true</overWriteReleases>
                            <overWriteSnapshots>true</overWriteSnapshots>
                        </configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>io.fabric8</groupId>
				<artifactId>docker-maven-plugin</artifactId>
				<version>0.25.0</version>
				<configuration>
					<images>
						<image>
							<alias>ebdocker</alias>
							<name>611429739415.dkr.ecr.eu-west-1.amazonaws.com/dwoproject:%l</name>
							<build>
								<dockerFileDir>${project.basedir}/src/main/docker</dockerFileDir>
								<assembly>
									<inline>
										<dependencySets>
											<dependencySet>
												<includes>
													<include>${project.groupId}:EBServer</include>
												</includes>
												<outputDirectory>.</outputDirectory>
												<outputFileNameMapping>ROOT.war</outputFileNameMapping>
											</dependencySet>
										</dependencySets>
									</inline>
								</assembly>
							</build>
							<run>
								<ports>
									<port>127.0.0.1:8080:80</port>
									<port>127.0.0.1:8009:8009</port>
								</ports>
<!-- 								<volumes> -->
<!-- 									<bind> -->
<!-- 										<volume>${project.basedir}/target/dependency:/usr/local/tomcat/webapps</volume> -->
<!-- 									</bind> -->
<!-- 								</volumes> -->
								<links>
									<link>mysql:mysql</link>
									<link>smtp:smtp</link>
								</links>
								<env>
									<RDS_PASSWORD>${mysql.password}</RDS_PASSWORD>
									<RDS_DB_NAME>${mysql.database}</RDS_DB_NAME>
									<DWO_REDIRECT>false</DWO_REDIRECT>
									<ENV_NOSEB>true</ENV_NOSEB>
									<ENV_IPRANGE>172.17.0.1</ENV_IPRANGE>
								</env>
								<namingStrategy>alias</namingStrategy>
							</run>
						</image>
					</images>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<packaging>pom</packaging>
</project>
