<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<properties>
		<revision>2.5.5-SNAPSHOT</revision>
	</properties>
	<parent>
		<groupId>nl.uu.fi.dwo</groupId>
		<artifactId>DWO.master.pom</artifactId>
		<version>1.1</version>
	</parent>
	<artifactId>EBDocker</artifactId>
	<version>${revision}</version>
	<name>Docker voor EBServer</name>
	<dependencies>
		<dependency>
			<groupId>nl.uu.fi.dwo</groupId>
			<artifactId>EBServer</artifactId>
			<version>${project.version}</version>
			<type>war</type>
		</dependency>
		<dependency>
		  <groupId>nl.numworx.osiris</groupId>
  		  <artifactId>osiris-import</artifactId>
  		  <version>0.0.6</version>
  		  <type>war</type>
		</dependency>
		<dependency>
		    <groupId>de.javakaffee.msm</groupId>
		    <artifactId>memcached-session-manager-tc8</artifactId>
		    <version>2.3.2</version>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>io.fabric8</groupId>
				<artifactId>docker-maven-plugin</artifactId>
				<version>0.38.0</version>
				<executions>
					<execution>
						<id>build</id>
						<phase>package</phase>
						<goals>
							<goal>build</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<images>
						<image>
							<alias>ebdocker</alias>
							<name>611429739415.dkr.ecr.eu-west-1.amazonaws.com/dwoproject:%l</name>
							<build>
								<dockerFileDir>${project.basedir}/src/main/docker</dockerFileDir>
								<assembly>
									<inline>
										<dependencySets>
											<dependencySet>
												<includes>
													<include>${project.groupId}:EBServer</include>
												</includes>
												<outputDirectory>.</outputDirectory>
												<outputFileNameMapping>ROOT.war</outputFileNameMapping>
											</dependencySet>
											<dependencySet>
												<includes>
													<include>nl.numworx.osiris:osiris-import</include>
												</includes>
												<outputDirectory>.</outputDirectory>
												<outputFileNameMapping>dwo#osiris-import.war</outputFileNameMapping>
											</dependencySet>
											<dependencySet>
												<includes>
													<include>de.javakaffee.msm:*</include>
													<include>net.spy:*</include>
												</includes>
												<outputDirectory>.</outputDirectory>
											</dependencySet>
										</dependencySets>
									</inline>
								</assembly>
							</build>
							<run>
								<ports>
									<port>127.0.0.1:8080:80</port>
									<port>127.0.0.1:8009:8009</port>
								</ports>
<!-- 								<volumes> -->
<!-- 									<bind> -->
<!-- 										<volume>${project.basedir}/target/dependency:/usr/local/tomcat/webapps</volume> -->
<!-- 									</bind> -->
<!-- 								</volumes> -->
								<links>
									<link>mysql:mysql</link>
									<link>memcached:memcached</link>
								</links>
								<env>
									<RDS_PASSWORD>${mysql.password}</RDS_PASSWORD>
									<RDS_DB_NAME>${mysql.database}</RDS_DB_NAME>
									<DWO_REDIRECT>false</DWO_REDIRECT>
									<ENV_NOSEB>true</ENV_NOSEB>
									<ENV_IPRANGE>172.17.0.1</ENV_IPRANGE>
									<MEMCACHED>memcached:11211</MEMCACHED>
								</env>
								<labels>
									<traefik.frontend.rule>Host:app.docker.localhost</traefik.frontend.rule>
								</labels>
								<namingStrategy>alias</namingStrategy>
							</run>
						</image>
					</images>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<packaging>pom</packaging>
	<profiles>
		<profile>
			<id>fresh</id>
			<properties>
				<docker.imagePullPolicy>always</docker.imagePullPolicy>			
			</properties>
		</profile>
	</profiles>
</project>
