namespace: numworx
resources:
- ../initdb/
- mysql-deployment.yaml
- mysql-pvc.yaml
- mysql-service.yaml
- ingress.yaml
patches:
- path: environment.yaml
components:
- ../metrics/grafana/loki
configMapGenerator:
- name: application
  behavior: merge
  envs:
  - application.properties
