namespace: numworx
resources:
- ../initdb/
- mysql-deployment.yaml
- mysql-pvc.yaml
- mysql-service.yaml
- ingress.yaml
patches:
- path: environment.yaml
components:
- ../metrics/grafana/loki
- ../metrics/grafana/prometheus
configMapGenerator:
- name: application
  behavior: merge
  envs:
  - application.properties
images:
- name: ghcr.io/utrechtuniversity/numworx-dwo-setup/dwoproject
  newTag: 3.0.0
- name: ghcr.io/utrechtuniversity/numworx-dwo-resources/cds
  newTag: 3.0.0
- name: ghcr.io/utrechtuniversity/numworx-dwo-setup/maintenance
  newTag: 3.0.0
- name: ghcr.io/utrechtuniversity/numworx-dwo-setup/initdb
  newTag: 3.0.0

