CATALINA_OPTS="$CATALINA_OPTS -DDWO_ENV=$DWO_ENV"
CATALINA_OPTS="$CATALINA_OPTS -DCDN_HOST=$CDN_HOST"
CATALINA_OPTS="$CATALINA_OPTS -DCDNURL=$CDNURL"
CATALINA_OPTS="$CATALINA_OPTS -DDWO_ELB=$DWO_ELB"
CATALINA_OPTS="$CATALINA_OPTS -DDWO_REDIRECT=$DWO_REDIRECT"

CATALINA_OPTS="$CATALINA_OPTS -DRDS_DB_NAME=$RDS_DB_NAME"
CATALINA_OPTS="$CATALINA_OPTS -DRDS_HOSTNAME=$RDS_HOSTNAME"
CATALINA_OPTS="$CATALINA_OPTS -DRDS_PASSWORD=$RDS_PASSWORD"
CATALINA_OPTS="$CATALINA_OPTS -DRDS_PORT=$RDS_PORT"
CATALINA_OPTS="$CATALINA_OPTS -DRDS_USERNAME=$RDS_USERNAME"

CATALINA_OPTS="$CATALINA_OPTS -DSMTP_AUTH=$SMTP_AUTH"
CATALINA_OPTS="$CATALINA_OPTS -DSMTP_EMAIL=$SMTP_EMAIL"
CATALINA_OPTS="$CATALINA_OPTS -DSMTP_PASSWORD=$SMTP_PASSWORD"
CATALINA_OPTS="$CATALINA_OPTS -DSMTP_PORT=$SMTP_PORT"
CATALINA_OPTS="$CATALINA_OPTS -DSMTP_SERVER=$SMTP_SERVER"
CATALINA_OPTS="$CATALINA_OPTS -DSMTP_TLS=$SMTP_TLS"
CATALINA_OPTS="$CATALINA_OPTS -DSMTP_USER=$SMTP_USER"

CATALINA_OPTS="$CATALINA_OPTS -DENV_IPRANGE=$ENV_IPRANGE"
CATALINA_OPTS="$CATALINA_OPTS -DENV_NOSEB=$ENV_NOSEB"

CATALINA_OPTS="$CATALINA_OPTS -Djava.security.egd=file:/dev/./urandom"
