apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- chat-deployment.yaml
- chat-service.yaml
- chat-ingress.yaml
configMapGenerator:
- name: chat-config
  files:
  - conf.d/chat-numworx.cfg.lua 
  - conf.d/http.cfg.lua
