<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<properties>
		<repository></repository>
		<docker.platform></docker.platform>
		<username>gcadmin</username>
		<password>test</password>
		<url>http://dwoproject/dwo/</url>
		<initdbVersion>3.0.0</initdbVersion> <!-- never a snapshot -->
	</properties>
	<parent>
		<groupId>nl.uu.fi.dwo</groupId>
		<artifactId>dwo.master.pom</artifactId>
		<version>3.0.0</version>
	</parent>
	<artifactId>initdb</artifactId>
	<version>3.0.0</version>
	<name>Docker Container voor Init DB</name>
	<dependencies>
		<dependency>
		  <groupId>nl.numworx</groupId>
  		  <artifactId>initdb</artifactId>
		  <version>${initdbVersion}</version>
		</dependency>
	</dependencies>
	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-resources-plugin</artifactId>
					<version>3.3.1</version>
				</plugin>				
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-jar-plugin</artifactId>
					<version>3.4.2</version>
				</plugin>				
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>3.13.0</version>
				</plugin>				
			</plugins>			
		</pluginManagement>
		<plugins>
			<plugin>
				<groupId>io.fabric8</groupId>
				<artifactId>docker-maven-plugin</artifactId>
				<version>0.43.4</version>
				<extensions>true</extensions>
		        <dependencies>
		            <dependency>
		                <groupId>com.amazonaws</groupId>
		                <artifactId>aws-java-sdk-core</artifactId>
		                <version>1.11.707</version>
		            </dependency>
		        </dependencies>
				<configuration>
					<images>
						<image>
							<alias>initdb</alias>
							<name>${repository}initdb:%l</name>
							<build>
							<from>eclipse-temurin:11-jre</from>
							<cmd><shell>java -jar /maven/initdb-${initdbVersion}.jar /properties/application.properties</shell></cmd>
							<buildx>
						          <platforms>
						            <platform>${docker.platform}</platform>
						          </platforms>
						        </buildx>
							  <assemblies>
								<assembly>
									<name>maven</name>
									<descriptorRef>dependencies</descriptorRef>
								</assembly>
								<assembly>
								  <name>properties</name>
								  <inline>
									<file>
								                <source>application.properties</source>
								                <outputDirectory>/</outputDirectory>
								                <filtered>true</filtered>
						            		</file>
								  </inline>
								</assembly>
							  </assemblies>
							</build>
							<run>
								<links>
									<link>mysql:mysql</link>
									<link>redis:redis</link>
								</links>
								<namingStrategy>alias</namingStrategy>
							</run>
						</image>
					</images>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<packaging>docker-build</packaging>
  	<repositories>
    	<repository>
			<id>numworx-dwo-runner</id>
			<url>https://maven.pkg.github.com/UtrechtUniversity/numworx-dwo-runner</url>
			<snapshots><enabled>true</enabled></snapshots>
    	</repository>
    </repositories>
	<profiles>
		<profile>
			<id>fresh</id>
			<properties>
				<docker.imagePullPolicy>always</docker.imagePullPolicy>			
			</properties>
		</profile>
		<profile>
			<id>arm64</id>
			<properties>
				<docker.platform>linux/arm64</docker.platform>
			</properties>
		</profile>
		<profile>
			<id>local</id>
			<properties>
				<docker.platform></docker.platform>
				<repository/>
			</properties>
		</profile>
		<profile>
			<id>aws</id>
			<properties>
				<repository>581490975307.dkr.ecr.eu-west-1.amazonaws.com/</repository>
			</properties>
		</profile>
		<profile>
			<id>scw</id>
			<properties>
				<repository>rg.nl-ams.scw.cloud/numworx/</repository>
			</properties>		
		</profile>
		<profile>
			<id>github</id>
			<properties>
				<repository>ghcr.io/utrechtuniversity/numworx-dwo-setup/</repository>
				<docker.platform>linux/arm64,linux/amd64</docker.platform>
			</properties>
		</profile>
	</profiles>
</project>
