apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: dwoproject
  name: dwoproject
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    run: dwoproject
status:
  loadBalancer: {}
