namespace: numworx
resources:
- namespace.yaml
- redis-deployment.yaml
- redis-service.yaml
- smtp-service.yaml
- smtp-deployment.yaml
- cds-deployment.yaml
- cds-service.yaml
- environment.yaml
- dwoproject-deployment.yaml
- dwoproject-service.yaml
