apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    description: "The service for tomcat cluster membership."
  name: tomcat-membership
spec:
  clusterIP: None
  selector:
    run: dwoproject
