apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: smtp
  name: smtp
spec:
  ports:
    - name: "25"
      port: 25
      targetPort: 25
  selector:
    io.kompose.service: smtp
status:
  loadBalancer: {}
